import "server-only";

import { createChat } from "@xdevplatform/chat-xdk";
import { Client } from "@xdevplatform/xdk";
import type { Credentials } from "@/lib/credentials";

/**
 * Reads an X group chat through the X Chat API.
 *
 * XChat conversations are end-to-end encrypted, so the server only ever holds
 * ciphertext: `/2/chat/conversations/:id/events` returns encoded events, and
 * they are decrypted here with the account's own keys. Those keys are not
 * generated by this app — they belong to the account and live in Juicebox,
 * unlocked with the PIN set in another X client.
 *
 * Everything comes back as data: real message ids, real timestamps, real
 * sender ids, and history that pages instead of having to be scrolled.
 */

const EVENTS_PER_PAGE = 100;

export type XMessage = {
	authorHandle?: string;
	authorName?: string;
	kind: "message" | "join" | "leave" | "system";
	sentAtIso?: string;
	sentAtLabel?: string;
	sequence: number;
	text: string;
	externalId?: string;
	outgoing?: boolean;
};

/**
 * The decryption half, kept separate from the fetching half.
 *
 * Unlocking an account's keys needs Juicebox and a real PIN, which no test can
 * stand up. Everything around it — paging the events, resolving who sent what,
 * ordering the result — is ordinary code, and this seam is what lets that part
 * be tested against a mock API without pretending the crypto was exercised too.
 */
export type ChatDecrypter = {
	decryptEvents(events: string[]): {
		messages: { event: XDecryptedEvent }[];
		errors?: Record<string, string>;
	};
};

export type XDecryptedEvent = {
	type?: string;
	id?: string;
	senderId?: string;
	createdAtMsec?: number;
	content?: { text?: string };
};

export type XConversationRead = {
	messages: XMessage[];
	participants: { handle?: string; name?: string; profileUrl?: string }[];
	title?: string;
	conversationId: string;
	/** False when a cap stopped us before the first message in the chat. */
	reachedStart: boolean;
	/** Events the SDK could not decrypt, usually an older key version. */
	undecrypted: number;
};

type PublicKey = {
	id?: string;
	user_id?: string;
	userId?: string;
	public_key?: string;
	publicKey?: string;
	public_key_version?: string;
	publicKeyVersion?: string;
	identity_public_key?: string;
	identityPublicKey?: string;
	identity_public_key_signature?: string;
	identityPublicKeySignature?: string;
	juicebox_config?: unknown;
	juiceboxConfig?: unknown;
};

/** The API answers in snake_case; the SDK types promise camelCase. Take either. */
function pick<T>(
	row: Record<string, unknown>,
	...names: string[]
): T | undefined {
	for (const name of names) {
		const value = row[name];
		if (value !== undefined && value !== null) return value as T;
	}
	return undefined;
}

export function xClient(credentials: Credentials) {
	if (!credentials.xAccessToken) {
		throw new Error("Connect your X account in Settings first.");
	}

	// X_API_BASE_URL points this somewhere else: a proxy of your own, or the
	// mock the tests run against.
	const baseUrl = process.env.X_API_BASE_URL;

	return new Client({
		accessToken: credentials.xAccessToken,
		...(baseUrl ? { baseUrl } : {}),
	});
}

/**
 * Serves the Juicebox realm tokens out of the account's own config.
 *
 * X returns `juicebox_config` alongside the public keys, and it carries the
 * realm token map. Pulling the token from there keeps unlocking a matter of
 * the user's OAuth session plus their PIN, with nothing else to stand up.
 */
function realmTokens(config: unknown) {
	const raw =
		typeof config === "string" ? config : JSON.stringify(config ?? {});

	let parsed: unknown;
	try {
		parsed = JSON.parse(raw);
	} catch {
		parsed = {};
	}

	const holder = (parsed ?? {}) as Record<string, unknown>;
	const mapJson =
		holder.key_store_token_map_json ?? holder.keyStoreTokenMapJson;

	let map: Record<string, string> = {};

	if (typeof mapJson === "string") {
		try {
			const decoded = JSON.parse(mapJson) as unknown;
			map = Object.fromEntries(
				Object.entries(
					(decoded as { token_map?: Record<string, string> })?.token_map ??
						(decoded as Record<string, string>),
				).filter(([, value]) => typeof value === "string"),
			) as Record<string, string>;
		} catch {
			map = {};
		}
	}

	return async (realmId: string) => {
		const token = map[realmId] ?? map[realmId.toLowerCase()];
		if (!token) {
			throw new Error(
				`No Juicebox token for realm ${realmId}. Re-connect your X account in Settings.`,
			);
		}
		return token;
	};
}

async function unlockedChat(
	credentials: Credentials,
	ownKeys: PublicKey,
	signing: ReturnType<typeof signingKeys>,
): Promise<ChatDecrypter> {
	if (!credentials.xChatPin) {
		throw new Error(
			"Your XChat PIN is not set. Add it in Settings — it unlocks the keys that decrypt this chat, and it never leaves this machine.",
		);
	}

	const config =
		pick<unknown>(
			ownKeys as Record<string, unknown>,
			"juicebox_config",
			"juiceboxConfig",
		) ?? credentials.xChatJuiceboxConfig;

	const chat = await createChat({
		juiceboxConfig:
			typeof config === "string" ? config : JSON.stringify(config),
		getAuthToken: realmTokens(config),
	});

	await chat.unlock(credentials.xChatPin);

	const ownVersion =
		pick<string>(
			ownKeys as Record<string, unknown>,
			"public_key_version",
			"publicKeyVersion",
		) ?? "";

	if (credentials.xUserId) chat.setIdentity(credentials.xUserId, ownVersion);
	chat.setCacheKeys(true);
	chat.setSigningKeys(signing);

	return chat as unknown as ChatDecrypter;
}

function signingKeys(rows: PublicKey[]) {
	return rows.flatMap((row) => {
		const record = row as Record<string, unknown>;
		const userId = pick<string>(record, "user_id", "userId", "id");
		const publicKey = pick<string>(
			record,
			"signing_public_key",
			"public_key",
			"publicKey",
		);
		const publicKeyVersion = pick<string>(
			record,
			"public_key_version",
			"publicKeyVersion",
		);
		const identityPublicKey = pick<string>(
			record,
			"identity_public_key",
			"identityPublicKey",
		);
		const identityPublicKeySignature = pick<string>(
			record,
			"identity_public_key_signature",
			"identityPublicKeySignature",
		);

		return userId && publicKey && publicKeyVersion
			? [
					{
						userId,
						publicKeyVersion,
						publicKey,
						identityPublicKey: identityPublicKey ?? "",
						identityPublicKeySignature: identityPublicKeySignature ?? "",
					},
				]
			: [];
	});
}

/** Group membership changes are where join dates come from. */
function kindOf(type: string | undefined, text: string): XMessage["kind"] {
	if (type === "message") return "message";
	if (type !== "groupChange") return "system";
	return /\bremoved\b|\bleft\b/i.test(text) ? "leave" : "join";
}

export async function listXConversations(credentials: Credentials) {
	const client = xClient(credentials);
	const response = await client.chat.getConversations();

	return (response.data ?? []).map((row) => {
		const record = row as unknown as Record<string, unknown>;
		return {
			id: String(pick<string>(record, "id") ?? ""),
			name: pick<string>(record, "name", "title") ?? "Untitled chat",
			isGroup: String(pick<string>(record, "id") ?? "").startsWith("g"),
		};
	});
}

export async function readXConversation(input: {
	credentials: Credentials;
	conversationId: string;
	maxEvents?: number;
	onProgress?: (events: number) => void;
	/** Swapped out in tests; the real one needs a Juicebox unlock. */
	openChat?: (
		credentials: Credentials,
		ownKeys: unknown,
		signing: unknown,
	) => Promise<ChatDecrypter>;
}): Promise<XConversationRead> {
	const { credentials, conversationId } = input;
	const maxEvents = input.maxEvents ?? 10_000;
	const client = xClient(credentials);

	if (!credentials.xUserId) {
		throw new Error("Connect your X account in Settings first.");
	}

	// 1. Page the encrypted events. The key events come back in meta and are
	//    what the SDK needs to derive each conversation key version.
	const encoded: string[] = [];
	const keyEvents = new Set<string>();
	let paginationToken: string | undefined;
	let reachedStart = true;

	while (encoded.length < maxEvents) {
		const page = await client.chat.getConversationEvents(conversationId, {
			maxResults: EVENTS_PER_PAGE,
			...(paginationToken ? { paginationToken } : {}),
			chatMessageEventFields: [
				"conversation_id",
				"created_at",
				"encoded_event",
				"id",
				"is_trusted",
				"sender_id",
			],
		});

		for (const event of page.data ?? []) {
			const value = pick<string>(
				event as unknown as Record<string, unknown>,
				"encoded_event",
				"encodedEvent",
			);
			if (value) encoded.push(value);
		}

		for (const key of page.meta?.conversationKeyEvents ?? [])
			keyEvents.add(key);

		input.onProgress?.(encoded.length);
		paginationToken = page.meta?.nextToken;

		if (!page.meta?.hasMore || !paginationToken) break;

		if (encoded.length >= maxEvents) {
			reachedStart = false;
			break;
		}
	}

	// 2. Everyone in the conversation, so their signatures can be checked and
	//    their handles put on the messages.
	const conversation = await client.chat.getConversation(conversationId);
	const record = conversation.data as unknown as Record<string, unknown>;
	const memberIds =
		pick<string[]>(record, "participant_ids", "participantIds", "member_ids") ??
		[];
	const ids = Array.from(new Set([...memberIds, credentials.xUserId]));

	const keys = await client.users.getPublicKeys(ids, {
		publicKeyFields: [
			"identity_public_key_signature",
			"juicebox_config",
			"public_key",
			"public_key_version",
			"signing_public_key",
		],
	});

	const keyRows = (keys.data ?? []) as unknown as PublicKey[];
	const own =
		keyRows.find((row) => {
			const owner = pick<string>(
				row as Record<string, unknown>,
				"user_id",
				"userId",
				"id",
			);
			return owner === credentials.xUserId;
		}) ?? keyRows[0];

	if (!own) throw new Error("X returned no public keys for your account.");

	const people = await client.users.getByIds(ids, {
		userFields: ["name", "username"],
	});
	const byId = new Map(
		((people.data ?? []) as unknown as Record<string, string>[]).map((user) => [
			String(user.id),
			user,
		]),
	);

	// 3. Decrypt, with the key events first so the keys are known before the
	//    messages that used them.
	const open = input.openChat ?? unlockedChat;
	const chat = await open(credentials, own, signingKeys(keyRows));

	const result = chat.decryptEvents([...keyEvents, ...encoded]);

	const participants = new Map<
		string,
		XConversationRead["participants"][number]
	>();
	const messages: XMessage[] = [];

	for (const decrypted of result.messages) {
		const event = decrypted.event;
		const text = event.content?.text?.trim();
		if (!text) continue;

		const senderId = event.senderId ?? "";
		const user = byId.get(senderId);
		const handle = user?.username;
		const kind = kindOf(event.type, text);

		if (handle) {
			participants.set(handle, {
				handle,
				name: user?.name,
				profileUrl: `https://x.com/${handle}`,
			});
		}

		messages.push({
			authorHandle: handle,
			authorName: user?.name,
			externalId: event.id,
			kind,
			outgoing: senderId === credentials.xUserId,
			sentAtIso: event.createdAtMsec
				? new Date(event.createdAtMsec).toISOString()
				: undefined,
			sequence: messages.length,
			text: text.slice(0, 8000),
		});
	}

	// The API pages newest first; the app wants the chat in the order it happened.
	messages.sort((a, b) => (a.sentAtIso ?? "").localeCompare(b.sentAtIso ?? ""));
	messages.forEach((message, index) => {
		message.sequence = index;
	});

	return {
		conversationId,
		messages,
		participants: Array.from(participants.values()),
		reachedStart,
		title: pick<string>(record, "name", "title"),
		undecrypted: Object.keys(result.errors ?? {}).length,
	};
}
